/**
 * LINK CONSTANTS
 * @type {string}
 */
export const LINK_INDEX_PENDING = 'LINK_INDEX_PENDING'
export const LINK_INDEX_SUCCESS = 'LINK_INDEX_SUCCESS'
export const LINK_INDEX_FAILURE = 'LINK_INDEX_FAILURE'
export const LINK_INDEX_NO_CONTENT = 'LINK_INDEX_NO_CONTENT'

export const LINK_CREATE_PENDING = 'LINK_CREATE_PENDING'
export const LINK_CREATE_SUCCESS = 'LINK_CREATE_SUCCESS'
export const LINK_CREATE_FAILURE = 'LINK_CREATE_FAILURE'
